config:
  learning_rate: 0.2
  cov_learning_rate: 0.5
  noise_std_dev: 1.5
  n_populations: 500
  n_individuals: 200
  n_timesteps_per_trajectory: 1
  record_iterations: 50

  algorithm: "CMA_ES"
  peel: 0
  environment: "RobotArm"
  environment_index: 1
  MOR_flag: True
  model: "FeedForwardNeuralNetwork"
  reward: "euclidean_distance"
  multiple_rewards: "euclidean_distance, collision"
  hidden_layer_activation: "selu"
  output_activation: "none"
  output_scale: 3

  n_hidden_layers: 1
  n_nodes_per_layer: 10
  input_size: 7
  output_size: 3

  visualize: False
  visualize_every: 200
  from_file: False
  params_file: 'ext/04-27-2018_21-09-04/params/params_180.py'
  save_every: 20

  visualize: False
  visualize_every: 200
