config:
  learning_rate: 0.2
  cov_learning_rate: 0.5
  noise_std_dev: 1.5
  n_populations: 200
  n_individuals: 50
  n_timesteps_per_trajectory: 1
  record_iterations: 50

  algorithm: "CMA_ES"
  peel: 0
  environment: "RobotArm"
  environment_index: 0
  MOR_flag: True
  model: "FeedForwardNeuralNetwork"
  reward: "euclidean_distance"
  multiple_rewards: "manhattan_distance, euclidean_distance"
  hidden_layer_activation: "selu"
  output_activation: "none"
  output_scale: 3

  n_hidden_layers: 1
  n_nodes_per_layer: 10
  input_size: 7
  output_size: 3

  visualize: False
  visualize_every: 200
  from_file: False
  params_file: 'ext/02-21-2018_18-14-54/params/params_0.py'
  save_every: 20
