default_config:
  learning_rate: 0.2
  noise_std_dev: 0.8
  n_populations: 500
  n_individuals: 5
  n_timesteps_per_trajectory: 30

  algorithm: "EntES"
  environment: "Maze"
  environment_index: 1
  MOR_flag: "True"
  model: "FeedForwardNeuralNetwork"
  reward: "binary"
  hidden_layer_activation: "selu"
  output_activation: "none"
  output_scale: 1

  n_hidden_layers: 1
  n_nodes_per_layer: 10
  input_size: 9
  output_size: 4

  from_file: False
  params_file: 'ext/02-21-2018_18-14-54/params/params_0.py'
  save_every: 20
