config:
  learning_rate: 0.2
  noise_std_dev: 0.4
  n_populations: 1000
  n_individuals: 10
  n_timesteps_per_trajectory: 40
  record_iterations: 50

  algorithm: "ES"
  environment: "MOGame"
  environment_index: 2
  model: "FeedForwardNeuralNetwork"
  reward: "mo_compound"
  MOR_flag: False
  multiple_rewards: "mo_time_score, mo_death, mo_success"
  hidden_layer_activation: "selu"
  output_activation: "softmax"
  output_scale: 1

  n_hidden_layers: 1
  n_nodes_per_layer: 10
  input_size: 500
  output_size: 5

  from_file: False
  params_file: 'ext/02-21-2018_18-14-54/params/params_0.py'
  save_every: 200

  visualize: True
  visualize_every: 200
